# Continous Integration setup for SU2.
# Tests with the SU2 develop branch when the TestCases repository is modified.

language: cpp

compiler:
    - g++

notifications:
    email:
        recipients:
            - padronas@stanford.edu
  
branches:
    only:
        - feature_TravisCI

env:
    global:
        CXXFLAGS=-O3
    matrix:
        # Serial build and test
        - CONFIGURE_COMMAND="./configure --prefix=$TRAVIS_BUILD_DIR"
          TEST_SCRIPT=serial_regression.py
        # Parallel build and test
        #- CONFIGURE_COMMAND="./configure --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=$TRAVIS_BUILD_DIR"
        #  TEST_SCRIPT=parallel_regression.py

before_install:
    # install the necessary packages
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy mpich2

install:
    # Get the code and compile it
    - git clone https://github.com/su2code/SU2.git
    - echo $TRAVIS_BUILD_DIR
    - pwd
    - ls







